[project]
name = "ocr-cli-scaffold"
version = "0.1.0"
requires-python = ">=3.10"
description = "CLI utilities for Aliyun and Qwen OCR comparison"
readme = "README.md"

[tool.pytest.ini_options]
addopts = "-ra"
testpaths = ["tests"]
pythonpath = ["."]
